language: python

install:
- pip install -r requirements.txt

script:
- ./build.sh

deploy:
  provider: pages
  local_dir: ./doc/build/html
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master
